wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: huggingface
    huggingface_version: 4.18.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.5
    start_time: 1653649629
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      4: 3.9.5
      5: 0.12.16
      6: 4.18.0
      8:
      - 5
