wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.4
    cli_version: 0.14.2
    framework: huggingface
    huggingface_version: 4.28.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1681456618.949717
    t:
      1:
      - 1
      - 3
      - 11
      - 49
      - 51
      - 55
      2:
      - 1
      - 3
      - 11
      - 49
      - 51
      - 55
      3:
      - 23
      4: 3.7.4
      5: 0.14.2
      6: 4.28.0
      8:
      - 5
